### ISSUE TITLE
自定义保存path，path建议改成相对output的目录

### ISSUE THREAD

**Issue by williamqian** [liuqianhonga/ComfyUI-Image-Compressor#3]
现在是相对comfyui安装根目录

**Comment by liuqianhonga** [comment]
@williamqian  现在默认存储的是ComfyUI output目录下的 compressed目录，可否提供截图说明下问题？

**Comment by williamqian** [comment]
> @williamqian 现在默认存储的是ComfyUI output目录下的 compressed目录，可否提供截图说明下问题？

你把compressed改成别的目录就会发现

**Comment by liuqianhonga** [comment]
> > @williamqian 现在默认存储的是ComfyUI output目录下的 compressed目录，可否提供截图说明下问题？
> 
> 你把compressed改成别的目录就会发现

@williamqian 确是如此，我已经修改并提交。
