### ISSUE TITLE
节点不一致

### ISSUE THREAD

**Issue by yyyuyyu** [liuqianhonga/ComfyUI-Image-Compressor#4]
为什么我的节点跟你的完全不一样 输出节点只有一个 什么也连接不了
![Uploading D842A594-ABC0-4679-B196-8F224B82EFB0.png…]()

**Comment by yyyuyyu** [comment]
保存图片以及改变输出图片的格式 不过现在也可以啦 谢谢

**Comment by yyyuyyu** [comment]
> @yyyuyyu 我用着images的输出节点并没有多大用处，在新的逻辑中已经移除了，文档已更新。你的使用场景是什么？

保存图片以及改变输出图片的格式 不过现在也可以啦 谢谢

**Comment by liuqianhonga** [comment]
> > @yyyuyyu 我用着images的输出节点并没有多大用处，在新的逻辑中已经移除了，文档已更新。你的使用场景是什么？
> 
> 保存图片以及改变输出图片的格式 不过现在也可以啦 谢谢

好的，使用着有什么问题，可以再反馈下
